### ISSUE TITLE
Configurable telnet port for healthcheck?

### ISSUE THREAD

**Issue by hvorragend** [docker-home-automation-stack/fhem-docker#3]
I am running several FHEM container and so I have to forward the ports like this:
```
5083:8083 (FHEMWEB)
5072:7072 (Telnet)
```

Your healthcheck-script is using the telnet port 7072 hardcoded. 

Could you please make this port configurable? Perhaps as an environment value?

**Comment by jpawlowski** [comment]
It actually shouldn't be necessary as each instance of the container image may use port 7072 in parallel since they are all having dedicated network interfaces. Should you decide to publish ports on the host interface, you may use different ports on the host to forward traffic to 7072 of the corresponding container instance. Your examples above look correct to do this.

**Comment by hvorragend** [comment]
BUT: When you are running the container in host mode, you can't forward these ports. 

Then I can choose other ports in FHEM. But not for your health check. Till now. I have seen your commits. Thank you.

**Comment by jpawlowski** [comment]
You shouldn't be running the container in host mode.
FHEM modules that may require extended access are running their own processes and are all designed to be run in a separate container. This is what you should be doing, that's what Docker is designed for.

**Comment by hvorragend** [comment]
Hallo Loredo, 
ich schreib es auf die Schnelle mal in deutscher Sprache. 

Ich weiß, dass man die Container "verbuddeln" sollte. So mache ich es auch mit meinem Produktiv-FHEM. Aber es gibt auch Installationen, die bspw. per FHEM2FHEM verbunden sind und im Host-Modus laufen müssen. 

- Sonos
- FakeRoku
- und sonstige Broadcast-Notwendigkeiten. 

Es geht also nicht immer ohne Host-Mode.
